### ISSUE TITLE
Please explain the use of the plugin

### ISSUE THREAD

**Issue by pcav** [mauroalberti/geocouche#1]
in more detail, in the About.
We'd be also grateful if you could check with other geology lugins to see if there is any scope for merging.
Thanks.

**Comment by mauroalberti** [comment]
First point: inserted a longer description in the About section. 
Second point: we plan to use geocouche _also_ as an embedded module in qgSurf and possibly qProf - for additional geological data orientations processing and plotting. So we need the maximum freedom in modify the internals of geocouche. For the immediate future, we therefore prefer avoid trying to merge this plugin with stereonet-related plugins from other developers.

**Comment by pcav** [comment]
Thanks. I respectfully disagree with the second point: coordinating with other takes certainly longer, but you get much further. From openness and collaboration we reach much bigger goals.
Would you like to start a public discussion on this? I'll be happy to facilitate it.

**Comment by mauroalberti** [comment]
Thanks for the suggestions and the kind offer to help. In this particular case however the first aim is developing a plugin that could be fully compatible with, and functional to, other already developed tools.  Productive collaborations with developers of other geological tools, similar or complementary, would be a successive step, surely welcome.
